# Generated by Django 3.1.4 on 2022-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20221020_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
