# Generated by Django 4.1.2 on 2022-10-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_auto_20221020_2346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
